### ISSUE TITLE
Exception when the resources are obtained via URL

### ISSUE THREAD

**Issue by seankenny** [seankenny/fullcalendar#6]
When the calendar is used via:

``` javascript
$('#calendar').fullCalendar({
  defaultView: 'resourceDay',
  resources:'/resources,
  events: [
  {
    title: 'R1-R2: Lunch 14.00-15.00',
    start: '2013-08-21T14:00:00.000Z',
    end: '2013-08-21T15:00:00.000Z',
    resources: ['r1','r2']
  }
});
```

then an exception is thrown:

``` javascript
ReferenceError: resources is not defined
    at addResourceSources (http://localhost:6297/Scripts/fullcalendar/fullcalendar.js:1332:17)
    at Calendar.ResourceManager (http://localhost:6297/Scripts/fullcalendar/fullcalendar.js:1316:9)
    at new Calendar (http://localhost:6297/Scripts/fullcalendar/fullcalendar.js:222:25)
    at HTMLDivElement.<anonymous> (http://localhost:6297/Scripts/fullcalendar/fullcalendar.js:166:28)
    at Function.jQuery.extend.each (http://localhost:6297/Scripts/jquery-1.10.2.js:657:23)
    at jQuery.fn.jQuery.each (http://localhost:6297/Scripts/jquery-1.10.2.js:266:17)
    at $.fn.fullCalendar (http://localhost:6297/Scripts/fullcalendar/fullcalendar.js:164:14)
```

**Comment by seankenny** [comment]
Fixed.
